### ISSUE TITLE
Access Token Javascript Client

### ISSUE THREAD

**Issue by jraristi** [aspnet/AzureSignalR-samples#101]
In the README is to be read: 

> This sample have been **deprecated**. Users are not recommended to generate access token by themselves. In the Serverless scenario, users are recommended to use Management SDK to build a negotiation server which is responsible for generating access token. For more samples and details, take [Management Sample](../Management) as reference.

What possibility is there to generate this access key on the client side?

**Comment by realwanpengli** [comment]
Hi @jraristi ,
Yes, 
```
var clientEndpoint = serviceManager.GetClientEndpoint("<Your Hub Name>");
var accessToken = serviceManager.GenerateClientAccessToken("<Your Hub Name>", "<Your User ID>");
```

More information can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#quick-start).

**Comment by jraristi** [comment]
Thanks a lot for the prompt answer!

I am having a problem and it is most likely because of this.

First of all, the client is Javascript. Is there a Service Manager library for Javascript?

I am still not using the Service Manager, but in my example, I can send serverlessly broadcast messages. Then via Insomnia or Postman I subscribe a client (javascript client):
`PUT https://<instance-name>.service.signalr.net/api/v1/hubs/<hub-name>/groups/<group-name>/users/<userid>`

userid (user1) is of course in the token of the javascript client:
```
var connection = new signalR.HubConnectionBuilder('https://<test-service>/client/?hub=chathub')
                                        .withUrl('/chathub', { accessTokenFactory: () => "jwt token" })
                                        .build();
```
JWT Content:

```
{
  "nameid": "user1",
  "nbf": 1563440272,
  "exp": 1563443872,
  "iat": 1563440272,
  "aud": "https://<test-service>/client/?hub=chathub"
}
```
In my example, I changed the C# Client for a Javascript. "broadcast" works, but the client won't get "send to group".

Could you please direct me to the right direction??

**Comment by jraristi** [comment]
Ok, I just read:

[here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md)

Is there a workaround for using a Javascript client?

**Comment by jraristi** [comment]
I posted a better description of my problem [here](https://stackoverflow.com/questions/57096974/azure-signalr-serverless-javascript-client-subscribe-to-a-group-via-rest-client).

Any heads up would be really appreciated.

**Comment by realwanpengli** [comment]
@jraristi 
> First of all, the client is Javascript. Is there a Service Manager library for Javascript?

There is no Service Manager library for Javascript for now. 

> Why a postman/insomia PUT request to subscribe to a group won't work? how do I subscribe to a group? From the client wouldn't be so safe.

Did you add the user to the group before sending group messages?
Rest API can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#api).


> Is there a workaround for using a Javascript client

If you have serverless scenario, I recommend you use [Azure Functions bindings for SignalR Service](https://github.com/Azure/azure-functions-signalrservice-extension). Chat samples(simple chat and auth-chat) can be found [here](https://github.com/Azure/azure-functions-signalrservice-extension/tree/dev/samples).
With this signalr binding extension, you don't need to generate signalr access token by yourself.

**Comment by jraristi** [comment]
In my modified example, I send messages to the group `groupname` every 5 seconds, then I subscribe to it and my expectation is to start getting messages after I used the REST call to subscribe to the `groupname`.

I generate the JWT Token for every REST call. The Audience always changes for every different REST call and it is generated by the example:

```
public string GenerateAccessToken(string audience, string userId, TimeSpan? lifetime = null)
        {
            IEnumerable<Claim> claims = null;
            if (userId != null)
            {
                claims = new[]
                {
                    new Claim(ClaimTypes.NameIdentifier, userId)
                };
            }

            return GenerateAccessTokenInternal(audience, claims, lifetime ?? TimeSpan.FromHours(1));
        }
```
Where the call to `GenerateAccessToken` is:
     `var client = _serviceUtils.GenerateAccessToken(url, _userId);`

Thus, the audience changes for every url generated.

The JWT for the SendMessage to a group is:

```
{
  "nameid": "PC4_2d8ee5971c9f420098599d6b019b17bf",
  "nbf": 1563521905,
  "exp": 1563525505,
  "iat": 1563521905,
  "aud": "https://test.service.signalr.net/api/v1/hubs/chathub/groups/groupname"
}
```
and the REST call to subscribe to the group is:

```
{
  "nameid": "PC4_10cdb31caf9442d89c12a84eef566a9e",
  "nbf": 1563520975,
  "exp": 1563524575,
  "iat": 1563520975,
  "aud": "https://test.service.signalr.net/api/v1/hubs/chathub/groups/groupname/users/user1"
}
```

**Comment by jraristi** [comment]
I will try tho the function bindings. Thanks a lot for the support!

**Comment by realwanpengli** [comment]
@jraristi Could you share your code? If the status code is 2xx, I guess you didn't add the user to group successfully. Is your http method for add-user-to-group request `PUT`? If you modified the `serverless` sample, please note that the [BuildRequest](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/Serverless/ServerHandler.cs#L142) is `POST` by default.
 
You can try this [new serverless sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management) which uses Mangement SDK. This one is easier to modify and contains more APIs and utilities. You can send messages in webcokets connection in Persistent mode. And the interfaces are just like aspnetcore signalr sdk.

**Comment by realwanpengli** [comment]
Did your client listen to the messages like this:
```
        connection.On<string, string>("GroupMessage",
                (string server, string message) =>
                {
                    Console.WriteLine($"[{DateTime.Now.ToString()}] Received message from server {server}: {message}");
                });
```
Are arguments' count and method name the same with the request?
Could you share your code?

**Comment by jraristi** [comment]
The server sends messages only messages to "sendMessages"

```
public ServerHandler(string connectionString, string hubName, string userId)
        {
            _userId = userId;
            _serverName = GenerateServerName();
            _serviceUtils = new ServiceUtils(connectionString);
            _hubName = hubName;
            _endpoint = _serviceUtils.Endpoint;

            _defaultPayloadMessage = new PayloadMessage
            {
                Target = "SendMessage",
                Arguments = new[]
                {
                    _serverName,
                    "Hello from server",
                }
            };
        }
```
[Here is my example](https://github.com/jraristi/serverless_example) 
In the line 56 of the server handler has the arg lines to send messages to a group:
``` 
var argLine = "send group groupname";
```
After the 3 message sent, the server uses the HTTP client to subscribe the "user1" (line 102):
```
if (count == 3)
                {
                    request = BuildPutRequest("https://test2-vncloud.service.signalr.net/api/v1/hubs/chathub/groups/groupname/users/user1");
                }
```

**Comment by realwanpengli** [comment]
@jraristi Your example works for me. 
I use the [Eppendorf.VNCloud.StatusDataPushService](https://github.com/jraristi/serverless_example/tree/master/Eppendorf.VNCloud.StatusDataPushService) to push group messages. 
And I use the [serverless client sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless) as client side. The client side command is `dotnet run -- client user1 -c "<connection string>" -h chathub`

---
> // Create a function that the hub can call to broadcast messages.
                connection.on('sendMessage', messageCallback);
                connection.on('echo', messageCallback);
                connection.onclose(onConnectionError);

The reason that you can't receives group messages:

The default message payload is 
```
            defaultPayloadMessage = new PayloadMessage
            {
                Target = "SendMessage",
                Arguments = new []
                {
                _serverName,
                "Hello from server",
                }
            };
```
which means your client connection listener should be
```
connection.on('SendMessage', (server, message) => {...});
```
But your target name (sendMessage) and the number (1) of arguments are incorrect.

**Comment by jraristi** [comment]
You are right! With the C# client, group messages reception works. Somehow, it doesn't work for the Javascript client :(

The parameter on 'SendMessage' is a callback with two parameters. I also tried with the explicit 2 parameters:
`connection.on('SendMessage', (server, message) => {...});`
With no success. I will keep researching but it seems strange.

**Comment by realwanpengli** [comment]
Then you should focus on the client code. I'd like to help if you share the client code with me.

**Comment by jraristi** [comment]
After testing it with the C# Client, it was clear to me, the server was Ok. The client code is also there [here](https://github.com/jraristi/serverless_example/tree/master/Eppendorf.VNCloud.StatusDataPushService.Client). 

The javascript code is in wwwroot/index.html

**Comment by jraristi** [comment]
Client JWT Token (which works for getting broadcasts):
```
{
  "nameid": "user1",
  "nbf": 1563440272,
  "exp": 1563443872,
  "iat": 1563440272,
  "aud": "https://test2-vncloud.service.signalr.net/client/?hub=chathub"
}
```

**Comment by realwanpengli** [comment]
@jraristi I found the [code for subscribing group](https://github.com/jraristi/serverless_example/search?q=subscribegroup&unscoped_q=subscribegroup) but no hub method implemented.

You mentioned you use Insomnia or Postman to subscribe a group for a user, could you show me the request?

**Comment by jraristi** [comment]
The code for the subscription of a group is made in the server code (just as a test).
I [this](https://github.com/jraristi/serverless_example/blob/master/Eppendorf.VNCloud.StatusDataPushService/ServerHandler.cs) file.
In the line 104:
`                    request = BuildPutRequest("https://test2-vncloud.service.signalr.net/api/v1/hubs/chathub/groups/groupname/users/user1");`

Is the PUT request built. The server runs a while(true) sending messages every 3 seconds and by the third request, the subscription request takes place:
```
                var request = BuildRequest(url);
                Thread.Sleep(3000);

                if (count == 3)
                {
                    request = BuildPutRequest("https://test2-vncloud.service.signalr.net/api/v1/hubs/chathub/groups/groupname/users/user1");
                }

                count++;
```
I tried this first with Postman and Insomnia with the right credentials and getting a 200 Status Code back.

**Comment by realwanpengli** [comment]
@jraristi 
200 means your subcribing group request is correct. Then the problem must be in client side.

The signalr client establish connection code should be like this:
```
 var connection = new signalR.HubConnectionBuilder()
      .withUrl('https://test2-vncloud.service.signalr.net/client/?hub=chathub', { accessTokenFactory: () => "<your token>" })
      .build();
```
Otherwise, the broswer's console will prompt errors:
```
Information: Normalizing '/chathub' to 'file:///chathub'.
``` 

But why you can receive broadcast messages? I don't think your client is connected to azure signalr service.

**Comment by jraristi** [comment]
Yes, I do get broadcast messages, but no messages when they are sent to the group (javascript client).
If I connect the C# client (from the serverless example), I do get the group and the broadcast messages.

That makes clear that the server implementation is Ok and I don't really see a difference between the javascript and C# clients...

**Comment by realwanpengli** [comment]
@jraristi 
I mean your code to establish client connection sounds incorrect:
```
var connection = new signalR.HubConnectionBuilder('https://test2-vncloud.service.signalr.net/client/?hub=chathub')
                                        .withUrl('/chathub', { accessTokenFactory: () => "xxx" })
                                        .build();
```

You could try:
```
var connection = new signalR.HubConnectionBuilder()
      .withUrl('https://test2-vncloud.service.signalr.net/client/?hub=chathub', { accessTokenFactory: () => "<your token>" })
      .build();
```

**Comment by jraristi** [comment]
Yes! That was it! Now it works!

Solution is: The connection of the Javascript was incorrect.

Thank you a lot for your support!
