### ISSUE TITLE
Usage: send user <userId>, send group <groupName>, broadcast

### ISSUE THREAD

**Issue by jraristi** [aspnet/AzureSignalR-samples#103]
Server is ran as:
`C:\temp\AzureSignalR-samples\samples\Serverless> dotnet run -- server -c "Endpoint=https://test2-vncloud.service.signalr.net;AccessKey=xxx;Version=1.0;" -h chat`

Client is ran as:
`C:\temp\AzureSignalR-samples\samples\Serverless>dotnet run -- client client1 -c "Endpoint=https://test2-vncloud.service.signalr.net;AccessKey=xxx;Version=1.0;" -h chat`

Usages I got to work:
```
broadcast
send user client1
```
What I couldn't got to work:
`send group groupname`

what groupname should I use to get the example (AzureSignalR-samples/samples/Serverless/) working?

**Comment by realwanpengli** [comment]
@jraristi Please remove the **accessKey**, and regenerate it, otherwise anyone can use your azure signalr service.
