### ISSUE TITLE
Issue when scaling out aspnetcore API with Azure Signal R service

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/AzureSignalR-samples#113]
See diagram

I have a multi tenant aspnet core solution, using Azure SignalR as a service.
There are 2 instances of the aspnetcore API. Each has a hub
When the user logs in to the API it gets a JWT with claims for user id, tenant id and session id (a unique GUID for each session). 
The signalr connection uses this same JWT.
When a user connects (signalr), I know throught the claims who they are, and I add the connection to three groups, one for the user (by userid), one for the tenant (by tenantid), and one for the session (by session guid).
When they disconnect I remove them from all three groups
Now I can send messages to the user, to the session and to the tenant.

Here the problem:

This works fine if I just have one instance of the API.
But if I scale out to 2, and one of the instances sends a message, sometimes it goes to the client, sometimes not.

I was under the impression that with SignalR as a service, the groups created and the connection/disonnection events where replicated between all hub instances, as they are when using say a Service Bus or SQL backplane for regular non Azure signalR. But that doesn't seem to be the case?

If I am right, can I not use Azure SignalR Service - do I need to revert back to using embeded SignalR with my own backplane?

![image](https://user-images.githubusercontent.com/3422637/65823561-4c0ec780-e20d-11e9-9caa-0feab0034ff7.png)

**Comment by vicancy** [comment]
> the groups created and the connection/disonnection events where replicated between all hub instances

No, only group created will be known by all the instances, not the connection/disconnection events. The connection/disconnection event is only triggered once on the instance which the client is actually connected to.

**Comment by johnkwaters** [comment]
OK. I think I have this working now, and it does work as expected. No matter which instance of the Hub a client connects to, the groups are propagated to all instances, and I can send a message to any of these groups from any instance, no matter which instance the client initially connected to. Nice!
