### ISSUE TITLE
How  to put configuration for primary and secondary connection string in AppSettings ?

### ISSUE THREAD

**Issue by riaadh** [aspnet/AzureSignalR-samples#125]
Hello, 
I want to use multiple instances of azure signalr 

In this documentation 
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-disaster-recovery

it says 

> Through config
> You should already know how to set SignalR service connection string through environment variables/app settings/web.cofig, in a config entry named Azure:SignalR:ConnectionString. If you have multiple endpoints, you can set them in multiple config entries, each in the following format:
> 
> 
> Copy
> Azure:SignalR:ConnectionString:<name>:<role>
> 

but i want the same thing but in appsetting format 
now i am using this  with only one connection and it works
  "Azure": {
    "SignalR": {
      "ConnectionString": ""
    }
  }

Thanks for help

**Comment by chenkennt** [comment]
You just need to convert the colon-separated configuration to a hierarchical configuration (which is a standard ASP.NET Core [convention](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#keys)):

Colon-separated:
```
Azure:SignalR:ConnectionString:<name>:<role>
```

appsettings.json
```
"Azure": {
  "SignalR": {
    "ConnectionString": {
      "<name>": {
        "<role>": "<connection_string>"
      }
    }
  }
}
```
