### ISSUE TITLE
Your Documentation For Your ChatRoom example is confusing

### ISSUE THREAD

**Issue by DataJuggler** [aspnet/AzureSignalR-samples#131]
You need a 'For Dummies' version of your Read Me file.

I read this, and you don't show an example of what 'Your Application Name' should be.

You also say 'Set Your ConnectionString', but do not show an example.

In [Startup.cs](Startup.cs), instead of calling `MapSignalR()`, you need to call `MapAzureSignalR({your_applicationName})` and pass in **connection string** to make the application connect to the service instead of hosting SignalR by itself. Replace `{**YourApplicationName**}` to the name of your application, this is the unique name to distinguish this application with your other application. You can use `this.GetType().FullName` as the value.

    ```cs
    public void Configuration(IAppBuilder app)
    {
        // Any connection or hub wire up and configuration should go here
        app.MapAzureSignalR(this.GetType().FullName);
    }

On my first Azure Service I created, I have Host Name and ConnectionString.

Do I enter Host Name for Application Name?

An Example is worth 100 pages of documentation to me.

Thank you for telling me what to put, since your documentation forced me to close down the app.

**Comment by DataJuggler** [comment]
You can close this ticket.

I got the app to run, but I don't see two chat windows I see one even if I run two instances.

WCF somehow seemed easier than this, at least it worked.

**Comment by chenkennt** [comment]
> ```cs
> public void Configuration(IAppBuilder app)
> {
>     // Any connection or hub wire up and configuration should go here
>     app.MapAzureSignalR(this.GetType().FullName);
> }

This is already a sample code you can use.
