### ISSUE TITLE
How to generate accesstoken for SignalR Rest APIs 

### ISSUE THREAD

**Issue by nebhagat** [aspnet/AzureSignalR-samples#139]
Hi,

I was redirected to these [samples](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless) from this [doc](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-rest-api#build-and-run-the-sample) for signalR REST Api reference.

This sample has deprecation warning stating not to generate access token by themselves, but to use `Management SDK`.
This SDK is only available in C# and my backend is in node.js.

I tried using signalR input binding in azure functions, [ref](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-input?tabs=javascript) and tried using access token generated by negotiation endpoint, but it threw authorization error.

What is the best way to generate access token for signalR Rest APIs in node js stack?

**Comment by chenkennt** [comment]
How access token should be generated is explained [here](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#authenticate-via-azure-signalr-service-accesskey).

If you're already familiar with JWT token, you can follow that information to sign a token with SignalR Service access key using any JWT library.

There is also a sample code in node.js [here](https://github.com/aspnet/AzureSignalR-samples/issues/42#issuecomment-404710602).
