### ISSUE TITLE
ChatRoomLocal readme seems to be missing something

### ISSUE THREAD

**Issue by danuw** [aspnet/AzureSignalR-samples#16]
When following all the instructions, on ```dotnet run```, the webpage displays ```Hello world!```.
It might be helpful to indicate to have to comment/remove that part from the Startup.cs just in case...?

```
// app.Run(async (context) =>
            // {
            //     await context.Response.WriteAsync("Hello World!");
            // });
```
as shown below

<img width="826" alt="screen shot 2018-05-09 at 21 57 38" src="https://user-images.githubusercontent.com/8134789/39839578-6dc9cf14-53d4-11e8-9d03-c9329786b33d.png">

**Comment by chenkennt** [comment]
Added a note to remove `app.Run(...)` in 413dc4d
