### ISSUE TITLE
How to use Azure SignalR Service from Azure Functions (v2) in C# ?

### ISSUE THREAD

**Issue by TonyHenrique** [aspnet/AzureSignalR-samples#17]
How to use **Azure SignalR Service** from **Azure Functions** (v2) in C# ?
Is there some documentation and sample?

**Comment by xscript** [comment]
Do you want to call the service REST API? or you want to host your hubs in `Azure Functions`?

**Comment by flowest** [comment]
I am also interested in this.
For me, i would like to trigger SignalR service from an Azure Function (preferably v1) (e.g. a HttpTrigger or EventGridTrigger) and send a message to all connected clients.
How to accomplish this?

**Comment by cecilphillip** [comment]
I'd be interested to see if we could run a serverless Hub in Azure Functions

**Comment by TonyHenrique** [comment]
I would like to trigger SignalR service from an Azure Function

**Comment by xscript** [comment]
You can refer to the [Realtime Signin Sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/RealtimeSignIn). It should have everything you need.
