### ISSUE TITLE
EventGrid sample is broken

### ISSUE THREAD

**Issue by markti** [aspnet/AzureSignalR-samples#179]
followed instructions to a tee. does not work. Is based on old / unsupported version of .net core 2.1

![image](https://user-images.githubusercontent.com/3155241/156257036-5a89b8b7-3d99-4628-a7e0-7e69b814f819.png)

![image](https://user-images.githubusercontent.com/3155241/156257050-0336c21a-a392-48c8-ad6c-ee7aa8c68605.png)

**Comment by vicancy** [comment]
fixed by https://github.com/aspnet/AzureSignalR-samples/pull/180/
