### ISSUE TITLE
Azure Signal R Adding User in Isolated Process

### ISSUE THREAD

**Issue by sharvaridesai123** [aspnet/AzureSignalR-samples#191]
# Question

We are using Azure Function apps using .Net 5 using Isolated process. We do want to use the SignlRService Output binding for sending to a user and sending to a group.

I am referencing [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-output?tabs=isolated-process&pivots=programming-language-csharp), The send to user says that not supported and also there are no examples provided. Can I get an update on whether this is still the case?

**Comment by Y-Sindo** [comment]
It is supported. We will update the doc soon and provide an example. Currently you can refer to this sample:
https://github.com/aspnet/AzureSignalR-samples/blob/main/samples/DotnetIsolated-BidirectionChat/Functions.cs#L76-L85 .

Thanks for the feedback.
