### ISSUE TITLE
Management Client sample needs refreshed

### ISSUE THREAD

**Issue by bretthacker** [aspnet/AzureSignalR-samples#227]
The management sample at https://github.com/aspnet/AzureSignalR-samples/blob/main/samples/Management/SignalRClient/README.md is over a year old. The readme indicates that Microsoft.Azure.SignalR.Management must be installed and indeed, this package is in NuGet and current. But this project doesn't reference that package. And the packages that are referenced are deprecated.

Is there a current code sample using the current Management library? I need to connect to an Azure SignalR instance in exactly this manner.

**Comment by Y-Sindo** [comment]
The SignalR client sample is used together with [MessagePublisher](https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/Management/MessagePublisher) sample to demonstrate the usage of management SDK. You can switch to [MessagePublisher](https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/Management/MessagePublisher) to get the usage of Management library. 

The README is corrected, and the `Microsoft.AspNetCore.SignalR.Client` is updated to 6.0.16. Given that `Microsoft.Extensions.CommandLineUtils` is deprecated and the alternative library `System.CommandLine` is still in preview, we'd rather keep this package.
