### ISSUE TITLE
ARM Creation of Azure Signalr Service 

### ISSUE THREAD

**Issue by DebolaA** [aspnet/AzureSignalR-samples#24]
Hello,

Aside from using Azure CLI or creating via Azure Portal; 

is there any  Powershell command or ARM way of creating the new Azure Signalr Service .

thank you.

**Comment by DebolaA** [comment]
@davidfowl kindly assist with the about question.

thank you

**Comment by xscript** [comment]
@ArieShout to provide more information on this.

**Comment by ArieShout** [comment]
The Azure PowerShell cmdlets for Azure SignalR service can be found at: https://www.powershellgallery.com/packages/AzureRM.SignalR/0.1.1-preview

Docs available at: https://github.com/Azure/azure-powershell/blob/AzureRM.SignalR.0.1.0/src/ResourceManager/SignalR/Commands.SignalR/help/AzureRM.SignalR.md

**Comment by xscript** [comment]
@DebolaA feel free to reopen this issue if you have more questions on this.
