### ISSUE TITLE
Examples for .NET Core Console App?

### ISSUE THREAD

**Issue by olavt** [aspnet/AzureSignalR-samples#30]
Could you add an example on how to connect to Azure SignalR from a .NET Core Console App? All the examples are currently for ASP.NET / JavaScript and how the connection is setup from .NET Core is well hidden in the frameworks.

**Comment by xscript** [comment]
@olavt Thanks for the feedback!
I assume you mean starting client connections from .NET Core Console App to Azure SignalR Service.

If you already have a console app working with self-hosted ASP.NET Core SignalR, you don't have to change anything in your console app.
The only change you need is to call `AddAzureSignalR` and `UseAzureSignalR` in your ASP.NET Core SignalR server and configure the connection string. Then your console app will be automatically connecting to Azure SignalR Service.

**Comment by xscript** [comment]
Add a link to the console app sample in [aspnet/SignalR](https://github.com/aspnet/SignalR) and close the issue.

**Comment by olavt** [comment]
I was looking for a sample with a console app connecting directly to the Azure SignalR Service with no ASP.NET Core SignalR Server involved.

**Comment by xscript** [comment]
Could you describe your scenario in more details?
Right now you always need an ASP.NET Core SignalR Server if you want duplex communication between your clients and your server.
If you only need to push messages from server to clients, then you can use our REST API without having a SignalR Server. [The real-time signin sample] is showing this pattern. The difference is the clients are using JavaScript.

**Comment by olavt** [comment]
The scenario is to use Azure SignalR service as a fast way to get messages / events from a publisher to consumers from pure console apps running without any web / GUI.

**Comment by xscript** [comment]
Sounds like your scenario is broadcast messages from server to clients. And the clients are from console app.

You can use [`HubConnection`](https://github.com/aspnet/SignalR/blob/dev/src/Microsoft.AspNetCore.SignalR.Client.Core/HubConnection.cs) to connect to Azure SignalR Service. Sample usage is at [here](https://github.com/aspnet/SignalR/blob/dev/samples/ClientSample/HubSample.cs#L34).
Two things are different from connecting to a self-hosted ASP.NET Core SignalR Server:
- URL is like [this](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/function/AzureSignalR.cs#L97).
- Use access token for authentication, which is generated like [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/function/AzureSignalR.cs#L102).
