### ISSUE TITLE
Data Generation

### ISSUE THREAD

**Issue by SteveFarmerJr** [aspnet/AzureSignalR-samples#31]
In the FlightPlan sample, it is unclear to me how to generate the flight data and/or derive the "DataFileUrl".  There seems to be a js file in the data folder, but the readme also refers to azure blob storage. I'm sure I'm missing something.

**Comment by xscript** [comment]
Add @chenkennt to provide detailed instructions.

**Comment by chenkennt** [comment]
The flight data file should be a json file stored in some online storage (e.g. Azure Storage). The js file is a sample generator to generate random flight data. I've added more details about flight data format in README (see c448158).

**Comment by xscript** [comment]
@SteveFarmerJr feel free to reopen this issue if you have more questions.
