### ISSUE TITLE
Windows or Console App client to consume azure signalr library sample Docs Request

### ISSUE THREAD

**Issue by vavjeeva** [aspnet/AzureSignalR-samples#37]
i am trying to implement an application that connects and talk between windows client app and xamarin android app using Azure SignalR library. i am not finding any sample for windows or console app client to consume azure signalr service? please provide some insights.

**Comment by xscript** [comment]
You can refer to this [code snippet](https://github.com/aspnet/SignalR/blob/master/samples/ClientSample/HubSample.cs#L34-L49).
Client code is the same when you connect to self-hosted SignalR or Azure SignalR Service.
