### ISSUE TITLE
No executable found matching command "dotnet-user-secrets"

### ISSUE THREAD

**Issue by MarekLani** [aspnet/AzureSignalR-samples#44]
In chat room sample I was experiencing No executable found matching command "dotnet-user-secrets" error, when trying to add Azure SignalR Service connection string to user-secrets. It was necessary to add following code to csproj file. 

```
  <ItemGroup>
	<DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
```

**Comment by davidfowl** [comment]
You might be using .net core 2.0. The latest sdk has this tool built into the sdk.
