### ISSUE TITLE
Realtime Sign-in Example using Azure SignalR Service - SignIn Hub Code

### ISSUE THREAD

**Issue by ericbrunner** [aspnet/AzureSignalR-samples#48]
Please Post a Full Sample (Source Code) Not only function.json that references a C# function dll. Thanks in advance.

**Comment by xscript** [comment]
You can find the source code at [here](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/RealtimeSignIn/function). Specifically, the function's source code is at [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/function/SignInFunction.cs).

**Comment by cnlogistics** [comment]
The source code of the Hub is missing.

scriptFile": "../RealtimeSignIn.dll",
  "entryPoint": "RealtimeSignIn.SignInFunction.Run"

I want the source code of that dll: RealtimeSignIn.dll
}

**Comment by xscript** [comment]
There is no C# `Hub` class in this example.

The page allows anonymous access. The `SignIn` function will generate authentication token for all clients in [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/function/SignInFunction.cs#L37-L41). Each client will use the token to authenticate with Azure SignalR Service in [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/content/index.html#L217). Also each client will listen on updates in the broadcast channel in [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/content/index.html#L210).

**Comment by cnlogistics** [comment]
Where is that "signin" specified in here?

await signalR.SendAsync("signin", "updateSignInStats", stats.TotalNumber, stats.ByOS, stats.ByBrowser);

Somewhere that hub has to be created or black magic is goinhmg on...

**Comment by xscript** [comment]
The `signin` is a logical hub in this sample. It will be created and maintained within Azure SignalR Service.
Because in the Serverless scenario, clients only listen for messages. So there is no need to have a web server and a C# `hub` hosted in the server.
From Azure SignalR Service perspective, the hub name is included in the URL, which is generated [here](https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/RealtimeSignIn/function/SignInFunction.cs#L39).

**Comment by cnlogistics** [comment]
So I could name the logical hub `mylogicalazure-signalr-hub` and it will work, too? Ok thanks @xscript for you intense clarifications.Well serverless sometimes make my head explode...

**Comment by xscript** [comment]
Yes, correct.

You are welcome. We are happy to help out. 😄

**Comment by cnlogistics** [comment]
Found that article which describes all very well https://www.c-sharpcorner.com/article/azure-signalr-messaging-with-net-core-console-app-server-and-client/

**Comment by xscript** [comment]
That's great. Do you get all you need? If so, please close the issue.

**Comment by ericbrunner** [comment]
@xscript Thanks for getting back. For others it would help if the official Microsoft documenation could be enhanced with perfect discription like the provided article. Currently the documention is very thin for Azure SignalR Service. I know you guys are before GA rollout but please forward the request to documention team.

**Comment by xscript** [comment]
@ericbrunner Thanks for the feedback!
We are aware of that our documentation is not in the perfect place yet. We will try our best to enrich documentation for GA.
