### ISSUE TITLE
Demo site shows map but no data

### ISSUE THREAD

**Issue by DynamicLTechnologySolutions** [aspnet/AzureSignalR-samples#50]
http://flightmap-demo1.azurewebsites.net/

**Comment by realwanpengli** [comment]
The animation is should be OK if the animation restarted. The server is created by @chenkennt ,  he knows the password to restart it.

**Comment by chenkennt** [comment]
Fixed.

**Comment by taeyo** [comment]
Can you check it again? Flight map site shows map but I can't see planes anymore. 
I want to share this demo in my technical session on Jan.11. 2019.

**Comment by realwanpengli** [comment]
Hi Taeyoung Kim,

I checked the http://flightmap-demo1.azurewebsites.net/ , planes are moving.

Thanks,
Wanpeng Li

**Comment by realwanpengli** [comment]
Hi Taeyoung Kim,

Can you try with other browser and machine?

Thanks,
Wanpeng Li

**Comment by realwanpengli** [comment]
You are welcome.
