### ISSUE TITLE
How to deploy service to Azure SignalR Service?

### ISSUE THREAD

**Issue by songxiaolei** [aspnet/AzureSignalR-samples#63]
I follow the instruction, try to deploy service to Azure SignalR Service.
https://github.com/aspnet/AzureSignalR-samples/tree/master/aspnet-samples/ChatRoom
When I run it with F5, it doesn't launch on Azure but localhost.

I check the Publisher menu, there are no option related Azure SignalR serivce.
There are 
App Service
Azure Virtual Machines
IIS, FTP, etc
Folder

**Comment by chenkennt** [comment]
You cannot really deploy application to Azure SignalR Service, instead you deploy to other Azure offerings like App service or VM and connect to SignalR service. It's recommended to use App service. Here is a doc about how to deploy it using Azure CLI, you can also deploy using Visual Studio:
https://github.com/aspnet/AzureSignalR-samples/blob/master/docs/azure-integration.md

**Comment by chenkennt** [comment]
Closing this it since there is no active discussion in this thread for a few months
