### ISSUE TITLE
Unable to connect with azure siganlr service

### ISSUE THREAD

**Issue by siuhleung7** [aspnet/AzureSignalR-samples#71]
I follow this github: [https://github.com/Azure-Samples/signalr-service-quickstart-serverless-chat](https://github.com/Azure-Samples/signalr-service-quickstart-serverless-chat)

After updated the **Microsoft.Azure.WebJobs.Extensions.SignalRService** to **1.0.0-preview1-10025**, then my connection will close instantly after connect.

I worked with: 
**Microsoft.Azure.WebJobs.Extensions.SignalRService**: **1.0.0-preview1-10002**
**Microsoft.AspNetCore.SignalR.Client**: 1.1.0

but now the azure signalr is no longer support 1.0.0-preview1-10002.

I updated 10025, then signalR client will always close the connection said
{Microsoft.AspNetCore.SignalR.HubException: The server closed the connection with the following error: No app server is currently connected to the Azure service.}

**Microsoft.Azure.WebJobs.Extensions.SignalRService**: **1.0.0-preview1-10025**
**Microsoft.AspNetCore.SignalR.Client**: 1.1.0

Don't know which combination is match... sad

**Comment by siuhleung7** [comment]
```
                    connection = new HubConnectionBuilder()
                        .WithUrl(connectionInfo.Content.url, options =>
                        {
                            options.AccessTokenProvider = () =>
                                Task.FromResult(connectionInfo.Content.accessToken);
                        }
                     )
                    .Build();
                     
                    connection.Closed += async (error) =>
                    {
                        await Task.Delay(new Random().Next(0, 5) * 1000);
                        await connection.StartAsync();
                    };

                    connection.On<Message>("newMessage", (message) =>
                    {
                        Console.WriteLine($"{message}");
                        //NewMessage(message);
                    });

                    connection.StartAsync();

    public class Message
    {
        public string sender;
        public string text;
    }

```

**Comment by siuhleung7** [comment]
Figure out that it is due to azure signalr endpoint issue, recreate new then problem solved.

**Comment by realwanpengli** [comment]
> Figure out that it is due to azure signalr endpoint issue
