### ISSUE TITLE
Live Flightmap demo is offline?

### ISSUE THREAD

**Issue by rfcdejong** [aspnet/AzureSignalR-samples#93]
Demo has been taken offline? It returns 404

http://flightmap-demo1.azurewebsites.net/

**Comment by rfcdejong** [comment]
Also https://signalrsignin.azurewebsites.net/ is offline

**Comment by chenkennt** [comment]
Fixed in #98

**Comment by rfcdejong** [comment]
Thank you, now I see that it is available under https://signalr-flightmap-demo.azurewebsites.net/
